name: Build and Deploy

on: 
  push:
    branches: [ master ]
    
jobs:
  build-and-deploy:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout our repo
          uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Deploy to Firebase
          uses: w9jds/firebase-action@manager
          with:
            args: deploy
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
